EnablePermanentActionBar: false
actionBarMessage: "PLAY.SERVERNAME.NET"
duration: 6 # Every how many ticks should the action bar appear? For it to be permanent, it must be no more than 40. 20 ticks = 1 real second

isBold: true
isItalic: false
isUnderline: false
isStrikethrough: false
isMagic: false

# IMPORTANT: If you do not want any colors, please set it to only white otherwise the plugin WILL break!! There must be at least one color listed at all times
# If more than one color is given, it will alternate between those colors every many ticks that is set in duration.
# Please find the full list of available colors here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
ChatColor:
  - GREEN
  - YELLOW
  - AQUA
  - LIGHT_PURPLE
  - RED
  - BLUE
  - WHITE
  - MAGIC
