name: ActionBarXtreme
version: '${project.version}'
main: com.me.actionbarxtreme.ActionBarXtreme
api-version: 1.13
commands:
  abx:
    description: View command list.
    aliases: []
  wavyactionbar:
    description: Test command.
    aliases: []
  testcommand:
    description: Test command2.
    aliases: []